<a href="https://colab.research.google.com/github/dc-dzekochris/numpy-introduction/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#what is numpy
is an open source library that forms the universal std of working with numerical data(matrix, vectors) and forms thr underlying foundation for libraries like pandas and matplotlib.

###numpy arrays
is the main data structure in numpy and has the following properties:
1. store a single data type
2. either one dimension or multidimensional
3. elements can be modified but they are fixed size hence cant change length

In [1]:
import numpy as np

In [2]:
# converting a python list to a numpy array
sales=[0,5,155,0,518,0,1827,616,317,325]
print(type(sales))

<class 'list'>


In [3]:
sales_array=np.array(sales)
print(type(sales_array))

<class 'numpy.ndarray'>


In [4]:
#properties
#ndim:no.of dimensions
#shape:rows and columns
#size: total no.of elements
#dtype: data type within the array
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

1
(10,)
10
int64


In [10]:
sales[[0, 5, 155, 0, 518],[0, 1827, 616, 317, 325]]
sales_array=np.array(sales)
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

TypeError: list indices must be integers or slices, not tuple

##numpy array creation
we use the following;
1.np.ones()
2.np.zeros
3.np.arrange
4.np.linspace
5.np.reshape

In [9]:
#ones: float by default
np.ones(5)


array([1., 1., 1., 1., 1.])

In [11]:
zeros=np.zeros(5,dtype=int)
zeros.dtype

dtype('int64')

In [14]:
#arange(start,stop,step)
np.arange(2,10,2).reshape(2,2)

array([[2, 4],
       [6, 8]])

In [13]:
#linspace
np.linspace(0,1000,5)

array([   0.,  250.,  500.,  750., 1000.])

###indexing and slicing numpy arrays


In [16]:
counties=["nairobi","kisumu","eldoret","kiambu","lamu","kwale","nakuru","nyeri"]
counties_array=np.array(counties).reshape(2,4)
counties_array

array([['nairobi', 'kisumu', 'eldoret', 'kiambu'],
       ['lamu', 'kwale', 'nakuru', 'nyeri']], dtype='<U7')

In [17]:
eldoret_county=counties_array[0,2]
eldoret_county

'eldoret'

In [18]:
lamu_county=counties_array[1,0]
lamu_county

'lamu'

In [19]:
#access for all (:) the record, the first 2 columns
counties_array.shape
counties_array[:,:2]

array([['nairobi', 'kisumu'],
       ['lamu', 'kwale']], dtype='<U7')

In [ ]:
#first record, all the columns
counties_array[0]

###filtering numpy arrays(conditions)

In [21]:
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [22]:
sales_array!=0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [23]:
condition=sales_array!=0
sales_array[condition]

array([   5,  155,  518, 1827,  616,  317,  325])

In [24]:
#filtering arrays with multiple conditions
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [25]:
(sales_array==616) |(sales_array<100)
sales_array[condition]

array([   5,  155,  518, 1827,  616,  317,  325])

In [28]:
#filtering using where (condition,ifblock,elseblock) condition
sales_inventory=np.array([12,18,102,0,0])
sales_inventory

array([ 12,  18, 102,   0,   0])

In [29]:
#where
np.where(sales_inventory<=0,"out of stock","in stock")

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

In [30]:
#products array
products_array=np.array(["egg","milk","bread","rice","beans"])
products_array

array(['egg', 'milk', 'bread', 'rice', 'beans'], dtype='<U5')

In [32]:
np.where(sales_inventory<=0,"out of stock",products_array)

array(['egg', 'milk', 'bread', 'out of stock', 'out of stock'],
      dtype='<U12')

###array aggregation methods
1.sum
2.mean
3.count
4.median
5.std
6.var
7.max
8.min

In [33]:
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [34]:
sales_array.sum()

3763

In [35]:
sales_array.min()

0

In [37]:
sales_array.max()

1827

In [39]:
sales_array.mean()


376.3

In [40]:
sales_array.std()

529.1366647662965

In [41]:
np.percentile(sales_array,[25,75])

array([  1.25, 469.75])